### PR TITLE
Duke multi-modules structure

### LINKED ISSUE #150: Modular project structure
This is a proposal to change the overall project structure creating separate modules (the change has been initially discussed in #147 ). The project structure will be something like this:

- **/** (project root, contains the parent pom file)
- **/duke-core** (core module, contains the core logic)
- **/duke-lucene** (depends from core, contains the lucene db implementation)
- **/duke-mapdb** (depends from core, contains the mapdb db implementation)
- **/duke-es** (depends from core, contains the elasticsearch db implementation). This is almost ready, I am working on it.
- **/duke-server** (depends from core, contains the server implementation)

New sub-modules (an example could be a python cleaner/comparator interpreter discussed #147)  could be easily added in a separate module.

This change implies that the default database will not be lucene anymore (can we set the InMemoryDatabase as the default one?). I would not keep the lucene dependency in the core because other modules (eg: duke-es) or projects using duke would indirectly use different version of lucene underneath.

WDYT? Can we create a separate branch to work on this?

### PR DESCRIPTION
**Pull request by drazzib**
Hi,

Here is my proposed PR which close #150 "Modular project structure".
This is largely inspired from @fabriziofortino modules list in #150.

* / (project root, contains the parent pom file)
* /duke-core (core module, contains the core logic)
* /duke-lucene (depends from core, contains the Lucene Database)
* /duke-mapdb (depends from core, contains the MapDB BlockingDatabase)
* /duke-mongodb (depends from core, contains the MongoDB DataSource)
* /duke-server (depends from core, contains the Server implementation)
* /duke-json (depends from core, contains the Jackson DataSource)
* /duke-jdbc (depends from core, contains the JDBC and JNDI DataSource and LinkDatabase impl)
* /duke-dist (assembly for ZIP packaging of all modukes)

I had to refactor ConfigWriter to move configuration handling to each DataSource implementation.
* Each DataSource implementation is responsible of writing its XML configuration using provided ConfigWriter instance.
* Each DataSource implementation should start with a specific tag (unique identifier of DataSource implementation inside Duke) and close it before returning.

Regards,

### CODE REVIEW

**Comment by fabriziofortino** [comment]
Thanks @drazzib ! It looks quite nice. I am going to test it in the week. I will add the ElasticSearch module as well.

@larsga any plan to work on this (bug fixing + doc update) and maybe plan an official release? Something like Duke 2.0?

**Comment by drazzib** [comment]
FTR, it will be difficult to maintain a large PR like this on the long run (I've already performed multiple merge from master).

So, I think we should try to merge this early to avoid any further divergence between branches.

**Comment by larsga** [comment]
I think this mostly looks very good. I think we should merge this module:

  * duke-jdbc (depends from core, contains the JDBC and JNDI DataSource and LinkDatabase impl)

in with the core, basically because it doesn't cause any extra dependencies. The refactor of ConfigWriter sounds right: basically there's no other way.

Are you OK with merging in that module? Can you do it within a couple of days? If so I can merge this in.

@fabriziofortino Yes, I have a plan for Duke 2.0. I've done some experiments (not on Github) and have some plans. This refactor was part of it, but now I don't have to do it, thanks to @drazzib

**Comment by drazzib** [comment]
Hi @larsga !

Thanks for your feedback. I've pushed my latest commit which re-integrate JDBC and JNDI into duke-core module.

**Comment by larsga** [comment]
I've been through this now, and it looks good. Thank you for the excellent work!

**Comment by larsga** [comment]
I'm raising the Duke 2.0 discussion on the mailing list.

**Pull request merged**
